services:
  web:
    build: .
    volumes:
      - log_files:/var/log/
    expose:
      - 5000
    env_file:
      - test.env
    command: python -m gunicorn app.run:app --workers=3 --bind 0.0.0.0:5000
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default-ssl.conf:/etc/nginx/conf.d/default.conf
      - log_files:/var/log/nginx
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: redis:latest
    expose:
      - 6379

  certbot:
    image: certbot/certbot
    volumes: 
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot -w /var/www/certbot --non-interactive --agree-tos -d %DOMAINNAME% -m %EMAIL%
    # Replace %DOMAINNAME% and %EMAIL% with actual domain name and email address

volumes:
  log_files:
  certbot-etc:
  certbot-var: