"""empty message

Revision ID: aa3b33ca09a1
Revises: d6dbc0bd77bb
Create Date: 2025-11-16 16:26:14.703506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3b33ca09a1'
down_revision = 'd6dbc0bd77bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('ip_hash', sa.String(), nullable=False),
    sa.Column('fp_hash', sa.String(), nullable=False),
    sa.Column('was_approved_before', sa.Boolean(), nullable=False),
    sa.Column('last_reviewed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_reviewed_by_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['admin_user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['requester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_note')
    op.drop_table('requester')
    # ### end Alembic commands ###
